name: Build and Deploy

on:
  push:
    tags:
      - "v*"

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Build
      run: dotnet build src/chttp/chttp.csproj --configuration ${{ env.CONFIGURATION }} -p:Version=${VERSION}
    - name: Pack
      run: dotnet pack src/chttp/chttp.csproj --configuration ${{ env.CONFIGURATION }} --no-self-contained --framework net7.0 -p:Version=${VERSION}
    - name: Push Nuget
      run: dotnet nuget push src/chttp/nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key $nuget_api_key --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
    - name: Publish
      run: |
        dotnet publish --configuration ${{ env.CONFIGURATION }} --self-contained --runtime win-x64 -p:Version=${VERSION}
        mv src/chttp/bin/Release/net7.0/win-x64/publish/chttp.exe src/chttp/bin/Release/net7.0/win-x64/publish/chttp-win-x64.exe
        mv src/chttp/bin/Release/net7.0/win-x64/publish/chttp.pdb src/chttp/bin/Release/net7.0/win-x64/publish/chttp-win-x64.pdb
        dotnet publish --configuration ${{ env.CONFIGURATION }} --self-contained --runtime win-arm64 -p:Version=${VERSION}
        mv src/chttp/bin/Release/net7.0/win-arm64/publish/chttp.exe src/chttp/bin/Release/net7.0/win-arm64/publish/chttp-win-arm64.exe
        mv src/chttp/bin/Release/net7.0/win-arm64/publish/chttp.pdb src/chttp/bin/Release/net7.0/win-arm64/publish/chttp-win-arm64.pdb
        dotnet publish --configuration ${{ env.CONFIGURATION }} --self-contained --runtime linux-x64 -p:Version=${VERSION}
        mv src/chttp/bin/Release/net7.0/linux-x64/publish/chttp src/chttp/bin/Release/net7.0/linux-x64/publish/chttp-linux-x64
        mv src/chttp/bin/Release/net7.0/linux-x64/publish/chttp.pdb src/chttp/bin/Release/net7.0/linux-x64/publish/chttp-linux-x64.pdb
        dotnet publish --configuration ${{ env.CONFIGURATION }} --self-contained --runtime linux-arm64 -p:Version=${VERSION}
        mv src/chttp/bin/Release/net7.0/linux-arm64/publish/chttp src/chttp/bin/Release/net7.0/linux-arm64/publish/chttp-linux-arm64
        mv src/chttp/bin/Release/net7.0/linux-arm64/publish/chttp.pdb src/chttp/bin/Release/net7.0/linux-arm64/publish/chttp-linux-arm64.pdb
        dotnet publish --configuration ${{ env.CONFIGURATION }} --self-contained --runtime linux-arm -p:Version=${VERSION}
        mv src/chttp/bin/Release/net7.0/linux-arm/publish/chttp.exe src/chttp/bin/Release/net7.0/linux-arm/publish/chttp-linux-arm
        mv src/chttp/bin/Release/net7.0/linux-arm/publish/chttp.pdb src/chttp/bin/Release/net7.0/linux-arm/publish/chttp-linux-arm.pdb
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
          files: |
            src/chttp/bin/Release/net7.0/win-x64/publish/chttp-win-x64.exe
            src/chttp/bin/Release/net7.0/win-x64/publish/chttp-win-x64.pdb
            src/chttp/bin/Release/net7.0/win-arm64/publish/chttp-win-arm64.exe
            src/chttp/bin/Release/net7.0/win-arm64/publish/chttp-win-arm64.pdb
            src/chttp/bin/Release/net7.0/linux-x64/publish/chttp-linux-x64
            src/chttp/bin/Release/net7.0/linux-x64/publish/chttp-linux-x64.pdb
            src/chttp/bin/Release/net7.0/linux-arm64/publish/chttp-linux-arm64
            src/chttp/bin/Release/net7.0/linux-arm64/publish/chttp-linux-arm64.pdb
            src/chttp/bin/Release/net7.0/linux-arm/publish/chttp-linux-arm
            src/chttp/bin/Release/net7.0/linux-arm/publish/chttp-linux-arm.pdb


        